-- Make hosts global (independent of users).
-- Policies become per-user-per-host assignments.
-- We recreate the policies table to avoid DB-specific constraint-name dependencies
-- when removing the old UNIQUE(host_id) constraint.

-- 1. Create new policies table with the correct structure
CREATE TABLE policies_v7 (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id            BIGINT NOT NULL,
    user_id            BIGINT NOT NULL,
    allowed_protocols  VARCHAR(32) NOT NULL DEFAULT 'TCP',
    port_range_min     INT NOT NULL,
    port_range_max     INT NOT NULL,
    max_rules          INT NOT NULL DEFAULT 5,
    CHECK (port_range_min <= port_range_max),
    CHECK (max_rules >= 1),
    CONSTRAINT uq_policy_user_host UNIQUE (user_id, host_id),
    FOREIGN KEY (host_id) REFERENCES hosts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 2. Migrate existing policies (derive user_id from hosts.user_id before we drop it)
INSERT INTO policies_v7 (host_id, user_id, allowed_protocols, port_range_min, port_range_max, max_rules)
SELECT p.host_id, h.user_id, p.allowed_protocols, p.port_range_min, p.port_range_max, p.max_rules
FROM policies p
JOIN hosts h ON h.id = p.host_id;

-- 3. Swap: drop old table, rename new one
DROP TABLE policies;
ALTER TABLE policies_v7 RENAME TO policies;

-- 4. Remove user_id from hosts (hosts are now global resources)
ALTER TABLE hosts DROP COLUMN user_id;
